import { IDynamicFieldConfig, ISelectOption } from "@/types/admin.types";

export const DIAMOND_SHAPE_OPTIONS: ISelectOption[] = [
  { value: "Round", label: "Round Brilliant" },
  { value: "Princess", label: "Princess Cut" },
  { value: "Cushion", label: "Cushion Cut" },
  { value: "Emerald", label: "Emerald Cut" },
  { value: "Oval", label: "Oval Cut" },
  { value: "Radiant", label: "Radiant Cut" },
  { value: "Pear", label: "Pear Cut" },
  { value: "Marquise", label: "Marquise Cut" },
  { value: "Asscher", label: "Asscher Cut" },
  { value: "Heart", label: "Heart Cut" },
];

export const DIAMOND_COLOR_OPTIONS: ISelectOption[] = [
  { value: "D", label: "D (Colorless - Grade 1)" },
  { value: "E", label: "E (Colorless - Grade 2)" },
  { value: "F", label: "F (Colorless - Grade 3)" },
  { value: "G", label: "G (Near Colorless - Top)" },
  { value: "H", label: "H (Near Colorless)" },
  { value: "I", label: "I (Near Colorless - Warm)" },
  { value: "J", label: "J (Near Colorless)" },
  { value: "K", label: "K (Faint Tint)" },
];

export const DIAMOND_CLARITY_OPTIONS: ISelectOption[] = [
  { value: "FL", label: "FL (Flawless)" },
  { value: "IF", label: "IF (Internally Flawless)" },
  { value: "VVS1", label: "VVS1 (Very Very Slightly Included 1)" },
  { value: "VVS2", label: "VVS2 (Very Very Slightly Included 2)" },
  { value: "VS1", label: "VS1 (Very Slightly Included 1)" },
  { value: "VS2", label: "VS2 (Very Slightly Included 2)" },
  { value: "SI1", label: "SI1 (Slightly Included 1)" },
  { value: "SI2", label: "SI2 (Slightly Included 2)" },
];

export const DIAMOND_CUT_OPTIONS: ISelectOption[] = [
  { value: "Ideal", label: "Ideal (Super-Ideal Optical)" },
  { value: "Excellent", label: "Excellent Symmetry & Fire" },
  { value: "Very Good", label: "Very Good" },
  { value: "Good", label: "Good" },
];

export const CERTIFICATION_LAB_OPTIONS: ISelectOption[] = [
  { value: "GIA", label: "GIA (Gemological Institute of America)" },
  { value: "IGI", label: "IGI (International Gemological Institute)" },
  { value: "AGS", label: "AGS (American Gem Society)" },
  { value: "HRD", label: "HRD (Antwerp World Diamond Centre)" },
];

export const POLISH_OPTIONS: ISelectOption[] = [
  { value: "Ideal", label: "Ideal" },
  { value: "Excellent", label: "Excellent" },
  { value: "Very Good", label: "Very Good" },
  { value: "Good", label: "Good" },
];

export const SYMMETRY_OPTIONS: ISelectOption[] = [
  { value: "Ideal", label: "Ideal" },
  { value: "Excellent", label: "Excellent" },
  { value: "Very Good", label: "Very Good" },
  { value: "Good", label: "Good" },
];

export const FLUORESCENCE_OPTIONS: ISelectOption[] = [
  { value: "None", label: "None (Inert)" },
  { value: "Faint", label: "Faint" },
  { value: "Medium", label: "Medium Blue" },
  { value: "Strong", label: "Strong Blue" },
];

export const DIAMOND_FORM_FIELDS: IDynamicFieldConfig[] = [
  {
    name: "name",
    label: "Diamond Designation / Name",
    type: "text",
    placeholder: "e.g. 2.05ct Round Brilliant Ideal Cut Lab Grown Diamond",
    required: true,
    colSpan: 2,
  },
  {
    name: "sku",
    label: "Vault SKU Identifier",
    type: "text",
    placeholder: "e.g. DG-RND-205",
    required: true,
    colSpan: 1,
  },
  {
    name: "shape",
    label: "Gemstone Shape / Cut Style",
    type: "select",
    options: DIAMOND_SHAPE_OPTIONS,
    required: true,
    colSpan: 1,
  },
  {
    name: "carat",
    label: "Carat Weight (ct)",
    type: "number",
    step: 0.01,
    min: 0.1,
    max: 50,
    placeholder: "1.00",
    required: true,
    colSpan: 1,
  },
  {
    name: "color",
    label: "Optical Color Grade",
    type: "select",
    options: DIAMOND_COLOR_OPTIONS,
    required: true,
    colSpan: 1,
  },
  {
    name: "clarity",
    label: "Purity Clarity Grade",
    type: "select",
    options: DIAMOND_CLARITY_OPTIONS,
    required: true,
    colSpan: 1,
  },
  {
    name: "cut",
    label: "Cut Grade Proportion",
    type: "select",
    options: DIAMOND_CUT_OPTIONS,
    required: true,
    colSpan: 1,
  },
  {
    name: "price",
    label: "Atelier Base Price (USD $)",
    type: "number",
    step: 50,
    min: 100,
    placeholder: "5000",
    required: true,
    colSpan: 1,
  },
  {
    name: "discountPercentage",
    label: "Collector Discount (%)",
    type: "number",
    step: 1,
    min: 0,
    max: 90,
    placeholder: "0",
    required: false,
    colSpan: 1,
  },
  {
    name: "lab",
    label: "Certification Laboratory",
    type: "select",
    options: CERTIFICATION_LAB_OPTIONS,
    required: true,
    colSpan: 1,
  },
  {
    name: "certificateNumber",
    label: "Certificate Inscription ID",
    type: "text",
    placeholder: "e.g. LG612849021",
    required: true,
    colSpan: 1,
  },
  {
    name: "length",
    label: "Length (mm)",
    type: "number",
    step: 0.01,
    min: 0.1,
    placeholder: "6.50",
    required: true,
    colSpan: 1,
  },
  {
    name: "width",
    label: "Width (mm)",
    type: "number",
    step: 0.01,
    min: 0.1,
    placeholder: "6.50",
    required: true,
    colSpan: 1,
  },
  {
    name: "depth",
    label: "Depth (mm)",
    type: "number",
    step: 0.01,
    min: 0.1,
    placeholder: "4.00",
    required: true,
    colSpan: 1,
  },
  {
    name: "tablePercentage",
    label: "Table (%)",
    type: "number",
    step: 0.5,
    min: 30,
    max: 90,
    placeholder: "57",
    required: true,
    colSpan: 1,
  },
  {
    name: "depthPercentage",
    label: "Depth Ratio (%)",
    type: "number",
    step: 0.5,
    min: 30,
    max: 90,
    placeholder: "61.5",
    required: true,
    colSpan: 1,
  },
  {
    name: "polish",
    label: "Facet Polish Quality",
    type: "select",
    options: POLISH_OPTIONS,
    required: true,
    colSpan: 1,
  },
  {
    name: "symmetry",
    label: "Optical Symmetry Quality",
    type: "select",
    options: SYMMETRY_OPTIONS,
    required: true,
    colSpan: 1,
  },
  {
    name: "fluorescence",
    label: "UV Fluorescence Level",
    type: "select",
    options: FLUORESCENCE_OPTIONS,
    required: true,
    colSpan: 1,
  },
  {
    name: "stockQuantity",
    label: "Available Vault Stock Units",
    type: "number",
    step: 1,
    min: 0,
    placeholder: "1",
    required: true,
    colSpan: 1,
  },
  {
    name: "featured",
    label: "Feature in Premier Curated Showcase",
    type: "switch",
    description: "Display lot prominently on homepage and catalog top picks.",
    colSpan: 2,
  },
  {
    name: "description",
    label: "Curator Gemological Description",
    type: "textarea",
    placeholder: "Detailed diamond description, optical properties, crystal clarity notes...",
    required: true,
    colSpan: 2,
  },
  {
    name: "images",
    label: "High-Resolution Atelier Gemstone Images",
    type: "image-list",
    description: "Add one or more CDN or direct URLs for high-resolution images.",
    required: true,
    colSpan: 2,
  },
];
